find_package(Git QUIET)
if(GIT_FOUND)
  execute_process(COMMAND ${GIT_EXECUTABLE} describe --tags --dirty
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    RESULT_VARIABLE GIT_EXIT_STATUS
    OUTPUT_VARIABLE GIT_DESCRIBE_VERSION
    OUTPUT_STRIP_TRAILING_WHITESPACE)

  if(NOT GIT_EXIT_STATUS)
    set(PROJECT_VERSION ${GIT_DESCRIBE_VERSION})
  endif()
endif()

if(NOT DEFINED PROJECT_VERSION)
  set(PROJECT_VERSION "0.0.0")
endif()

string(REGEX REPLACE "^([0-9]+)\\..*" "\\1" VERSION_MAJOR "${PROJECT_VERSION}")
string(REGEX REPLACE "^[0-9]+\\.([0-9]+).*" "\\1" VERSION_MINOR "${PROJECT_VERSION}")
string(REGEX REPLACE "^[0-9]+\\.[0-9]+\\.([0-9]+).*" "\\1" VERSION_PATCH "${PROJECT_VERSION}")
set(VERSION_SHORT "${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}")
