name: ci
on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "LICENSE"
  release:
    types: [published]
  push:
    tags:
      - "*"
    branches:
      - main
      - develop

env:
  VERBOSE: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2022
          - ubuntu-24.04
        compiler:
          - llvm-20
          - gcc-14
        generator:
          - "Ninja"
        build_type:
          - Release
          - Debug
        exclude:
          - os: windows-2022
            compiler: gcc-14
          - os: windows-2022
            compiler: llvm-20
        include:
          - os: windows-2022
            compiler: msvc
            generator: "Visual Studio 17 2022"
            build_type: Release

          - os: windows-2022
            compiler: msvc
            generator: "Visual Studio 17 2022"
            build_type: Debug

    steps:
      - name: Install dependencies
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: sudo apt-get install -y libx11-dev libtbb-dev

      - uses: actions/checkout@v4

      - name: Setup Cache
        uses: ./.github/actions/setup_cache
        with:
          compiler: ${{ matrix.compiler }}
          build_type: ${{ matrix.build_type }}
          generator: ${{ matrix.generator }}

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows' )}}
          cmake: true
          ninja: true
          vcpkg: ${{ contains(matrix.os, 'windows' )}}
          ccache: true
          clangtidy: true
          cppcheck: true
          gcovr: ${{ contains(matrix.os, 'ubuntu') }}
          opencppcoverage: ${{ contains(matrix.os, 'windows') }}

      - name: Create Build Environment
        run: cmake -E make_directory ${{ runner.workspace }}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{ runner.workspace }}/build
        run: |
          cmake -G "${{ matrix.generator }}" $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE:STRING=${{ matrix.build_type }} -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        working-directory: ${{ runner.workspace }}/build
        shell: bash
        run: cmake --build . --parallel ${{ env.nproc }} --config ${{ matrix.build_type }}
